import React, { useMemo } from 'react';
import { ComposableMap, Geographies, Geography, Marker, Line } from 'react-simple-maps';
import { motion, AnimatePresence } from 'framer-motion';

const GEO_URL = "https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json";

// Approximate coordinates for regions
const REGIONS = {
    "US-East": [-75, 40],
    "US-West": [-120, 37],
    "EU-West": [2, 48],
    "Asia-Pac": [139, 35],
    "SA-East": [-46, -23],
};

const MapVisualizer = ({ selectedServer, attacks = [] }) => {
    const targetCoords = REGIONS[selectedServer] || [0, 0];

    return (
        <div className="w-full h-full bg-[#050510] relative overflow-hidden rounded-xl border border-cyber-dim shadow-[0_0_20px_rgba(0,240,255,0.1)]">
            {/* Decorative Grid Background */}
            <div className="absolute inset-0 bg-[linear-gradient(rgba(0,240,255,0.03)_1px,transparent_1px),linear-gradient(90deg,rgba(0,240,255,0.03)_1px,transparent_1px)] bg-[size:40px_40px] pointer-events-none" />

            <ComposableMap
                projection="geoMercator"
                projectionConfig={{
                    scale: 120,
                    center: [0, 20] // Adjust slightly to center the view
                }}
                style={{ width: "100%", height: "100%" }}
            >
                <Geographies geography={GEO_URL}>
                    {({ geographies }) =>
                        geographies.map((geo) => (
                            <Geography
                                key={geo.rsmKey}
                                geography={geo}
                                fill="#12121a"
                                stroke="#2a2a35"
                                strokeWidth={0.5}
                                style={{
                                    default: { outline: "none" },
                                    hover: { fill: "#1a1a25", outline: "none" },
                                    pressed: { outline: "none" },
                                }}
                            />
                        ))
                    }
                </Geographies>

                {/* Attack Lines */}
                <AnimatePresence>
                    {attacks.map((attack) => (
                        <AttackLine key={attack.id} attack={attack} target={targetCoords} />
                    ))}
                </AnimatePresence>

                {/* Target Marker */}
                {selectedServer && (
                    <Marker coordinates={targetCoords}>
                        <motion.circle
                            r={3}
                            fill="#00f0ff"
                            animate={{ r: [3, 8, 3], opacity: [0.5, 1, 0.5] }}
                            transition={{ duration: 1.5, repeat: Infinity }}
                        />
                        <motion.circle
                            r={6}
                            fill="none"
                            stroke="#00f0ff"
                            strokeWidth={1}
                            animate={{ r: [6, 12], opacity: [1, 0] }}
                            transition={{ duration: 1.5, repeat: Infinity }}
                        />
                    </Marker>
                )}

            </ComposableMap>

            {/* Map Overlay Vignette */}
            <div className="absolute inset-0 pointer-events-none bg-[radial-gradient(circle_at_center,transparent_20%,#050510_100%)]" />
        </div>
    );
};

// Sub-component for individual attack lines
const AttackLine = ({ attack, target }) => {
    return (
        <Line
            from={attack.source}
            to={target}
            stroke="#ff003c"
            strokeWidth={1}
            strokeLinecap="round"
            style={{
                filter: "drop-shadow(0 0 2px #ff003c)"
            }}
        // Framer motion doesn't work directly on react-simple-maps Line (which renders SVG path)
        // But we can use motion.path if we manually rendered the path.
        // React-simple-maps Line is a wrapper. Let's use standard line with motion.
        // Actually, Line component just returns a path.
        />
    );
};

// Creating a Custom Animated Line because react-simple-maps Line is static
const AnimatedAttackLine = ({ attack, target }) => {
    // We need to use lines that look like they are travelling.
    // Using motion.path with pathLength or just moving a circle along the path.
    // For simplicity in this text-based env, we will try a simple dasharray animation via CSS or Framer.

    // Actually, to correctly render a line on the map projection, we need the path string generated by the projection.
    // react-simple-maps exposes the projection via context if we use the Hook but ComposableMap doesn't easily expose it to children unless wrapped.

    // ALTERNATIVE: Just use straight lines or generic curves unrelated to projection if we want simple 'missile' look.
    // But ComposableMap handles projection.
    // Let's stick to the Line component but add a key to re-render or animate it?
    // Let's try passing `initial` and `animate` props if it spreads them?
    // Use `strokeDasharray` animation.

    return (
        <Line
            from={attack.source}
            to={target}
            stroke="#ff003c"
            strokeWidth={2}
            strokeLinecap="round"
            strokeDasharray="4 4"
            animate={{ strokeDashoffset: [20, 0] }}
            transition={{ duration: 0.5, repeat: Infinity, ease: "linear" }}
            // @ts-ignore
            component={motion.path}
        />
    )
}


export default MapVisualizer;
